# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-30 17:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(verbose_name='id пользователя')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('change', models.IntegerField(default=0, verbose_name='изменение счета')),
                ('target', models.CharField(default='Не указано', max_length=50)),
                ('balance', models.IntegerField(editable=False, verbose_name='Денег на счету')),
            ],
            options={
                'verbose_name': 'История счета',
                'db_table': 'account_user',
                'verbose_name_plural': 'История счета',
            },
        ),
        migrations.CreateModel(
            name='ExtensionUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_level', models.IntegerField(default=0, verbose_name='Стартовый капитал')),
                ('redzone', models.IntegerField(default=0, help_text='Сумма ден. средств, ниже которой нельзя опускаться', verbose_name='Красная зона')),
                ('greenzone', models.IntegerField(default=1000, help_text='выше этой суммы - все в порядке с финансами, ниже и до красной зоны - \n\t\tминимальная зона комфорта', verbose_name='Зона комфорта')),
                ('balance', models.IntegerField(default=0, editable=False, verbose_name='Денег на счету')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Расширение таблицы User',
                'db_table': 'ext_user',
                'verbose_name_plural': 'Расширения таблицы User',
            },
        ),
        migrations.CreateModel(
            name='NegativeTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='не указано', max_length=50)),
                ('status', models.BooleanField(default=False, verbose_name='Общая цель или частная')),
                ('user_id', models.PositiveIntegerField(verbose_name='id пользователя')),
            ],
            options={
                'verbose_name': 'Цель снятия средств',
                'db_table': 'negative_target',
                'verbose_name_plural': 'Цели снятия средств',
            },
        ),
    ]
