# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-30 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', verbose_name='Комментарий')),
                ('state', models.PositiveIntegerField(choices=[(1, 'В работе'), (2, 'Готово')], default=1, verbose_name='Состояние завки')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Дата обработки')),
            ],
            options={
                'verbose_name': 'Обработка обращения',
                'db_table': 'process_support',
                'verbose_name_plural': 'Обработка обращений',
            },
        ),
        migrations.CreateModel(
            name='TechSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_message', models.PositiveSmallIntegerField(choices=[(1, 'Предложения'), (2, 'Ошибка')], db_index=True, default=2, verbose_name='Тип сообщения')),
                ('feedback_mail', models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail для обратной связи')),
                ('caption', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Заголовок')),
                ('text', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата обращения')),
                ('files', models.ImageField(blank=True, null=True, upload_to='tech/%Y/%m/%d')),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name': 'Техподдержка',
                'db_table': 'tech_support',
                'verbose_name_plural': 'Техподдержка',
            },
        ),
        migrations.AddField(
            model_name='processsupport',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tech.TechSupport', verbose_name='Обращение'),
        ),
    ]
