# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-31 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='techsupport',
            name='closed',
            field=models.BooleanField(default=False, editable=False, verbose_name='Задача закрыта'),
        ),
    ]
